# Generated by Django 5.1.2 on 2024-11-11 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
