# Generated by Django 5.1.3 on 2024-11-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto_membros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='membros',
        ),
    ]
