# Generated by Django 5.1.3 on 2024-11-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_projeto_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
