# Generated by Django 5.1.2 on 2024-11-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_anexo_arquivo_alter_anexo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='nome',
            new_name='titulo',
        ),
    ]
